name: build images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - images/**

permissions:
  packages: write
  contents: read

jobs:
  build:
    name: Build ${{ matrix.name }} (${{ matrix.variant }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "SteamCMD Interactive"
            image: steamcmd
            variant: interactive
            dockerfile: Dockerfile.interactive
            tags: |
              ghcr.io/shardbyte/steamcmd:interactive
              docker.io/shardbyte/steamcmd:interactive
          - name: "SteamCMD Non-Interactive"
            image: steamcmd
            variant: noninteractive
            dockerfile: Dockerfile.noninteractive
            tags: |
              ghcr.io/shardbyte/steamcmd:noninteractive
              docker.io/shardbyte/steamcmd:noninteractive
              ghcr.io/shardbyte/steamcmd:latest
              docker.io/shardbyte/steamcmd:latest
          - name: "Docker ARK Server"
            image: docker-ark
            variant: default
            dockerfile: Dockerfile
            tags: |
              ghcr.io/shardbyte/docker-ark:latest
              docker.io/shardbyte/docker-ark:latest
          - name: "ARKManager"
            image: arkmanager
            variant: pelican
            dockerfile: Dockerfile.pelican
            tags: |
              ghcr.io/shardbyte/arkmanager:pelican
              docker.io/shardbyte/arkmanager:pelican
          - name: "ARKManager DEV"
            image: arkmanager
            variant: dev
            dockerfile: Dockerfile.dev
            tags: |
              ghcr.io/shardbyte/arkmanager:dev
              docker.io/shardbyte/arkmanager:dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            build:
              - images/${{ matrix.image }}/**

      - name: Repository owner to lowercase
        if: steps.changes.outputs.build == 'true'
        id: lower-repo
        run: echo "repository=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        if: steps.changes.outputs.build == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.changes.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: steps.changes.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.changes.outputs.build == 'true'
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/${{ matrix.image }}
          file: ./images/${{ matrix.image }}/${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ matrix.tags }}
